package seng202.team3.models;

import java.util.ArrayList;
import java.util.List;

/**
 * This class represents a list of wines generated by a search (stored as Wine objects in a Wine list)
 * @author Krishna Sridhar
 */

public class SearchWineList extends WineList {
    private List<Wine> searchWineList;

    /**
     * Constructs new SearchWineList object and initializes the list.
     */
    public SearchWineList() {
        searchWineList = new ArrayList<>();
    }

    /**
     * Used to access the list of searched wines.
     * @return list of wines returned from a search query
     */
    @Override
    public List<Wine> getWineList() {
        return searchWineList;
    }

    /**
     * Adds a wine to the searched wine list
     * @param wine object to be added
     */
    @Override
    public void addWineToList(Wine wine) {
        searchWineList.add(wine);
    }

    /**
     * Removes a wine from the searched wine list
     * @param wine object to be removed
     */
    @Override
    public boolean removeWineFromList(Wine wine) {
        return searchWineList.remove(wine);
    }

}
