package seng202.team3.models;

/**
 * This class represents a list of wines generated by a search (stored as Wine objects in a Wine list)
 *
 * @author Krishna Sridhar (nsr36)
 */

public class SearchWineList extends WineList {

    /**
     * implementation of abstract method
     *
     * @return "SearchWineList"
     */
    @Override
    public String getWineListName() {
        return "SearchWineList";
    }

}
