package seng202.team3.models;

import java.util.List;
import java.util.stream.Collectors;

/**
 * This class represents a list of wines generated by a search (stored as Wine objects in a Wine list)
 *
 * @author Krishna Sridhar (nsr36)
 */

public class SearchWineList extends WineList {

    /**
     * The keywords entered into the search bar
     */
    private String keywords;

    /**
     * The minimum year of wines in the search
     */
    private int minYear;

    /**
     * The maximum year of wines in the search
     */
    private int maxYear;

    /**
     * The minimum price of wines in the search
     */
    private float minPrice;

    /**
     * The maximum price of wines in the search
     */
    private float maxPrice;

    /**
     * The country of the wines in the search
     */
    private String country;

    /**
     * The colour of the wines in the search
     */
    private String colour;

    /**
     * The fullness of the wines in the search
     */
    private String fullness;

    /**
     * The name of the grape (variety) used in the search
     */
    private String grapeName;

    /**
     * Constructor for the SearchWineList, sets all the search attributes to the given values
     * TODO Replace default min max values to get from the database
     *
     * @param keywords the keywords that were entered into the search bar
     * @param minYear the minimum year entered for the search
     * @param maxYear the maximum year entered for the search
     * @param minPrice the minimum price entered for the search
     * @param maxPrice the maximum price entered for the search
     * @param country the country entered for the search
     * @param colour the colour entered for the search
     * @param fullness the fullness entered for the search
     * @param grapeName the name of the grape (variety) entered for the search
     */
    public SearchWineList(List<String> keywords, Integer minYear, Integer maxYear, Float minPrice, Float maxPrice,
                          String country, String colour, String fullness, String grapeName) {
        this.minYear = (minYear != null) ? minYear : 2007;
        this.maxYear = (maxYear != null) ? maxYear : 2019;
        this.minPrice = (minPrice != null) ? minPrice : 0f;
        this.maxPrice = (maxPrice != null) ? maxPrice : 0f;
        this.country = (country != null) ? country : "All";
        this.colour = (colour != null) ? colour : "All";
        this.fullness = (fullness != null) ? fullness : "All";
        this.grapeName = (grapeName != null) ? grapeName : "All";

        if (keywords != null) {
            this.keywords = String.join(" ", keywords);
        } else {
            this.keywords = "";
        }
    }

    /**
     * implementation of abstract method
     *
     * @return "SearchWineList"
     */
    @Override
    public String getWineListName() {
        return "SearchWineList";
    }

    /**
     * Gets and returns the keywords from the search bar
     *
     * @return keywords
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * Gets and returns the minimum year entered for the search
     *
     * @return minYear
     */
    public int getMinYear() {
        return minYear;
    }

    /**
     * Gets and returns the maximum year entered for the search
     *
     * @return maxYear
     */
    public int getMaxYear() {
        return maxYear;
    }

    /**
     * Gets and returns the minimum price entered for the search
     *
     * @return minPrice
     */
    public float getMinPrice() {
        return minPrice;
    }

    /**
     * Gets and returns the maximum price entered for the search
     *
     * @return maxPrice
     */
    public float getMaxPrice() {
        return maxPrice;
    }

    /**
     * Gets and returns the country entered for the search
     *
     * @return country
     */
    public String getCountry() {
        return country;
    }

    /**
     * Gets and returns the fullness entered for the search
     *
     * @return fullness
     */
    public String getFullness() {
        return fullness;
    }

    /**
     * Gets and returns the colour entered for the search
     *
     * @return colour
     */
    public String getColour() {
        return colour;
    }

    /**
     * Gets and returns the name of the grape entered for the search
     *
     * @return grapeName
     */
    public String getGrapeName() {
        return grapeName;
    }

    /**
     * Sets the keywords to the given String.
     * Used by the WineManager instance to change the keywords to have the correct capitalisation
     *
     * @param keywords the keywords from the search bar
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords;
    }

}
